services:
  # Наш S3-совместимый сторадж (замена AWS S3 для локальных тестов)
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  rest:
    image: tabulario/iceberg-rest:latest
    container_name: rest
    environment:
      - CATALOG_WAREHOUSE=/home/iceberg/warehouse

  # Spark with Iceberg
  spark:
    image: tabulario/spark-iceberg:latest
    container_name: spark
    ports:
      - "8888:8888" # Jupyter Notebook
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    depends_on:
      - minio
      - rest
    volumes:
      - .:/home/iceberg/local